import streamlit as st
# Input fitur numerik
featureA = st.number_input('Masukkan nilai untuk featureA')
featureB = st.number_input('Masukkan nilai untuk featureB')
featureC = st.number_input('Masukkan nilai untuk featureC')
featureD = st.number_input('Masukkan nilai untuk featureD')
featureE = st.number_input('Masukkan nilai untuk featureE')
featureF = st.number_input('Masukkan nilai untuk featureF')
featureG = st.number_input('Masukkan nilai untuk featureG')
featureH = st.number_input('Masukkan nilai untuk featureH')
featureI = st.number_input('Masukkan nilai untuk featureI')
compositionA = st.number_input('Masukkan nilai untuk compositionA')
compositionB = st.number_input('Masukkan nilai untuk compositionB')
compositionC = st.number_input('Masukkan nilai untuk compositionC')
compositionD = st.number_input('Masukkan nilai untuk compositionD')
compositionE = st.number_input('Masukkan nilai untuk compositionE')
compositionF = st.number_input('Masukkan nilai untuk compositionF')
compositionG = st.number_input('Masukkan nilai untuk compositionG')
compositionH = st.number_input('Masukkan nilai untuk compositionH')
compositionI = st.number_input('Masukkan nilai untuk compositionI')
compositionJ = st.number_input('Masukkan nilai untuk compositionJ')
