import streamlit as st
# Input fitur numerik
featureA = st.number_input('featureA')
featureB = st.number_input('featureB')
featureC = st.number_input('featureC')
featureD = st.number_input('featureD')
featureE = st.number_input('featureE')
featureF = st.number_input('featureF')
featureG = st.number_input('featureG')
featureH = st.number_input('featureH')
featureI = st.number_input('featureI')
compositionA = st.number_input('compositionA')
compositionB = st.number_input('compositionB')
compositionC = st.number_input('compositionC')
compositionD = st.number_input('compositionD')
compositionE = st.number_input('compositionE')
compositionF = st.number_input('compositionF')
compositionG = st.number_input('compositionG')
compositionH = st.number_input('compositionH')
compositionI = st.number_input('compositionI')
compositionJ = st.number_input('compositionJ')
